---
title: Tom Newton – Portfolio
timezone: Europe/London
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  work:
    title: Work
    output: false
    permalink: "/:title/"
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
email: hello@iamtomnewton.com
description: 'Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.

'
baseurl:
url: iamtomnewton.com
twitter_username: iamtomnewton
github_username: iamtomnewton
markdown: kramdown
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
sass:
  style: expanded
permalink: "/blog/:title/"


defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "work"
      type: "work" # previously `page` in Jekyll 2.2.
    values:
      layout: "work" # overrides previous default layout
